AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Environment:
      Variables:
        REDIS_HOST: host.docker.internal
        REDIS_PORT: 6379

Resources:
  SaveCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: card-api/
      Handler: app.saveCard
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /card
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
  GetCardFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: card-api/
      Handler: app.getCard
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /card
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
